## Esna 84{-}

- Location: North-east door, left side
- Date: Probably Domitian
- [Hieroglyphic Text](https://www.ifao.egnet.net/uploads/publications/enligne/Temples-Esna002.pdf#page=248){target="_blank"}
- Bibliography: None

<div class="col2">  
^1^ *[...]  *  
*[...kȝ.t ʿ.wy?]=f  *  
*grg spȝ.wt nỉw.wt  *  
    
*ḏd.ỉn Rʿ n [zȝ]=f šw  *  
*šm=k [...]  *  
*[...]=k tȝš n nṯr nb n=f  *  
  
*ḫntỉ=sn r nỉw.wwt rsy.wt  *  
*r bw nty ỉw mw.t-nṯr ỉm  *  
*rsy-nỉw.t pw  *  
  
*ḏd.ỉn šw n Rʿ  *  
*s.t tn tȝ pw  [...]  *  

^1^ [...]  
[...the work of] his [hands?]  
settles nomes and cities.  

Then Re said to his [son], Shu:  
May you go [...]  
you [...] the area of every god for him.  
  
They went upstream to the southern cities,  
  to where the Mother of God (Neith) was,  
That is: the South City (*Rs-n.t*).  
  
Then Shu said to Re:  
This place is the land of [...]  

</div>
<div class="col2">
 ^2^ [....]  
 *[...ḏd].tw [ḫnt]-tȝ  *  
   *m rn n spȝ.t tn  *  
   
 *ḫpr ḫnsw ḏḥwtỉ m s.t tn  *  
 *m ḥb dndn  *  
   *m-ẖnw pr pn ḥr=s*  
   *r-mn hrw pn  *  

^2^ [...]  
Thus one [says Khent]-ta  
   as the name of this district;  
     
Khonsu and Thoth came about in this place  
   for the Festival of Fury  
     within this temple for that reason,  
   until today.  
   
</div>
<div class="col2">

^3^ [...]   
[...] *sḫȝ ỉb=sn   *  
 *ḥnʿ ỉt=sn mw.t=sn  *  

^4^ [...]  
*nḥm.tw n kȝ=s   *  
*[...]  *  
*[ʿq m pr] pn   *  
 *[m wrḏ?]-ỉb  *  
 *pr=f m snb-ỉb  *  
   
*sḫr.w n tȝ-r-ḏr=f   *  
 *m ḥr=s  *  

^3^ [...]  
[...] their hearts recall,  
 with their father and mother.  
   
^4^ [...]  
one rejoices for her Ka [...]  
[...]  
[if one enters th[is [temple]  
 [in ill] health(?),  
 he leaves it in good health.  
  
The condition of the entire world  
 is before her face.  
</div>